export type {
  RegisteredAgent,
  AgentCapability,
  AgentTrustLevel,
  A2ATask,
  TaskIntent,
  TaskStatus,
  TaskPriority,
  TaskError,
  AgentRegisterRequest,
  AgentRegisterResponse,
  TaskSubmitRequest,
  TaskSubmitResponse,
  TaskUpdateRequest,
  TaskUpdateResponse,
  TaskStatusResponse,
  CapabilitiesResponse,
  PlatformIntent,
  AgentContext,
  ContextStoreRequest,
  ContextStoreResponse,
  ContextQueryResponse,
  RoutingPolicy,
  AgentScore,
  RoutingCandidate,
  RoutingResult,
  TaskRouteRequest,
  TaskRouteResponse,
} from './types';

export { authenticateAgent, generateAgentApiKey, getServiceDb } from './auth';
export {
  agentRegisterSchema,
  taskSubmitSchema,
  taskUpdateSchema,
  taskRouteSchema,
  taskFeedbackSchema,
  VALID_STATUS_TRANSITIONS,
  contextStoreSchema,
  contextQuerySchema,
} from './validation';
export type { ContextStoreInput, ContextQueryInput, TaskRouteInput, TaskFeedbackInput } from './validation';
export { executeIntent, isIntentSupported, listPlatformIntents, IntentNotFoundError } from './executor';
export {
  scoreCapabilityMatch,
  scoreRecency,
  scoreAgent,
  routeTask,
  fetchRoutingCandidates,
  fetchRoutingCandidatesWithReputation,
} from './router';
export type { TrustBlender, VersionContext } from './router';
export {
  submitTaskFeedback,
  getAgentReputation,
  getReputationScores,
  getReputationLeaderboard,
  blendTrustAndReputation,
  createReputationBlender,
} from './reputation';
export type { TaskFeedback, AgentReputation, SubmitFeedbackParams } from './reputation';
export {
  checkRateLimit,
  getAgentUsage,
  rateLimitHeaders,
  rateLimitBody,
  QUOTA_TIERS,
} from './rate-limiter';
export type {
  RateLimitAction,
  QuotaTier,
  RateLimitResult,
  AgentUsageSummary,
} from './rate-limiter';
export {
  createWorkflowDefinition,
  triggerWorkflow,
  advanceWorkflow,
  getWorkflowExecution,
  handleStepTaskCompletion,
  validateDAG,
  evaluateCondition,
  interpolateTemplate,
  computeProgress,
  getStepCategories,
  getWorkflowDefinition,
} from './workflow-engine';
export type {
  WorkflowDefinition,
  WorkflowExecution,
  WorkflowStatus,
  StepExecution,
  StepStatus,
  WorkflowStepDefinition,
  StepCondition,
  StepRetryPolicy,
  StepAgentTarget,
  CreateWorkflowRequest,
  TriggerWorkflowRequest,
  TriggerWorkflowResponse,
  WorkflowExecutionResponse,
} from './workflow-types';

// ── Channels (Agent-to-Agent Messaging) ──
export {
  channelCreateSchema,
  channelListSchema,
  channelAddMemberSchema,
  messageSendSchema,
  messageListSchema,
} from './channels';
export type {
  ChannelType,
  A2AChannel,
  MemberRole,
  ChannelMember,
  MessageType,
  VoteValue,
  ChannelMessage,
  ProposalTally,
  ChannelCreateRequest,
  ChannelCreateResponse,
  ChannelListResponse,
  ChannelAddMemberRequest,
  ChannelAddMemberResponse,
  MessageSendRequest,
  MessageSendResponse,
  MessageListResponse,
  ChannelCreateInput,
  ChannelListInput,
  ChannelAddMemberInput,
  MessageSendInput,
  MessageListInput,
} from './channels';

// ── Contracts (Agent Service Agreements) ──
export {
  proposeContract,
  negotiateContract,
  checkCompliance,
  listContracts,
  getContractDetail,
  terminateContract,
  findActiveContract,
  contractProposeSchema,
  contractNegotiateSchema,
  contractListSchema,
  contractTerminateSchema,
  DEFAULT_SLA,
} from './contracts';
// ── Discovery (Agent Search & Health) ──
export {
  searchAgents,
  getAgentProfile,
  recordHeartbeat,
  updateAgentProfile,
  computeAvailability,
} from './discovery';
export type {
  AgentAvailability,
  AgentHeartbeat,
  AgentHeartbeatRecord,
  AgentProfile,
  AgentSearchParams,
  AgentSearchResult,
  AgentProfileUpdate,
} from './discovery';
export {
  agentSearchSchema,
  agentHeartbeatSchema,
  agentProfileUpdateSchema,
} from './validation';
export type {
  AgentSearchInput,
  AgentHeartbeatInput,
  AgentProfileUpdateInput,
} from './validation';

export type {
  ServiceSLA,
  ServiceContract,
  ContractStatus,
  ContractPricing,
  PricingModel,
  ContractCompliance,
  SLAViolation,
  NegotiationEntry,
  NegotiationAction,
  ContractProposeRequest,
  ContractProposeResponse,
  ContractNegotiateRequest,
  ContractNegotiateResponse,
  ContractListResponse,
  ContractDetailResponse,
  ContractProposeInput,
  ContractNegotiateInput,
  ContractListInput,
  ContractTerminateInput,
} from './contracts';

// ── Governance (Agent Autonomy & Safety) ──
export {
  createPolicy,
  listPolicies,
  deactivatePolicy,
  evaluateAction,
  evaluateAgainstPolicy,
  matchesGlobList,
  matchGlob,
  isWithinTimeWindows,
  resolveEscalation,
  listEscalations,
  queryAuditLog,
  activateKillSwitch,
  liftKillSwitch,
  AUTONOMY_RANK,
  policyCreateSchema,
  policyListSchema,
  evaluateActionSchema,
  escalationResolveSchema,
  auditQuerySchema,
  killSwitchSchema,
  killSwitchLiftSchema,
} from './governance';
export type {
  AutonomyLevel,
  GovernedAction,
  TimeWindow,
  SpendLimit,
  GovernancePolicy,
  PolicyDecision,
  PolicyEvaluation,
  EvaluationRequest,
  EscalationStatus,
  EscalationRequest,
  GovernanceAuditEntry,
  SuspensionStatus,
  AgentSuspension,
  PolicyCreateRequest,
  PolicyCreateResponse,
  PolicyListResponse,
  EvaluateRequest,
  EvaluateResponse,
  EscalationResolveRequest,
  EscalationResolveResponse,
  AuditListResponse,
  KillSwitchRequest,
  KillSwitchResponse,
  KillSwitchLiftRequest,
  KillSwitchLiftResponse,
  PolicyCreateInput,
  PolicyListInput,
  EvaluateActionInput,
  EscalationResolveInput,
  AuditQueryInput,
  KillSwitchInput,
  KillSwitchLiftInput,
} from './governance';

// ── Billing (Token Economy & Ledger) ──
export {
  getOrCreateWallet,
  getWallet,
  setWalletStatus,
  deposit,
  computeCost,
  settleTask,
  listTransactions,
  getSpendSummary,
  depositSchema,
  settleTaskSchema,
  costEstimateSchema,
  transactionListSchema,
} from './billing';
export type {
  AgentWallet,
  WalletStatus,
  LedgerTransaction,
  TransactionType,
  TransactionStatus,
  SettlementResult,
  CostEstimate,
  SpendSummary,
  WalletResponse,
  DepositRequest,
  DepositResponse,
  SettleTaskRequest,
  SettleTaskResponse,
  TransactionListResponse,
  SpendSummaryResponse,
  CostEstimateRequest,
  CostEstimateResponse,
  DepositInput,
  SettleTaskInput,
  CostEstimateInput,
  TransactionListInput,
} from './billing';

// ── Auctions (Task Marketplace & Bidding) ──
export {
  createAuction,
  listAuctions,
  getAuctionDetail,
  placeBid,
  awardAuction,
  cancelAuction,
  withdrawBid,
  evaluateBids,
  computeDutchPrice,
  auctionCreateSchema,
  auctionListSchema,
  bidCreateSchema,
  auctionAwardSchema,
  DEFAULT_EVALUATION_WEIGHTS,
} from './auctions';
export type {
  AuctionType,
  AuctionStatus,
  TaskAuction,
  EvaluationWeights,
  BidStatus,
  AuctionBid,
  BidScoreBreakdown,
  AuctionCreateRequest,
  AuctionCreateResponse,
  AuctionListResponse,
  AuctionDetailResponse,
  BidCreateRequest,
  BidCreateResponse,
  AuctionAwardRequest,
  AuctionAwardResponse,
  AuctionCancelResponse,
  AuctionCreateInput,
  AuctionListInput,
  BidCreateInput,
  AuctionAwardInput,
} from './auctions';

// ── Delegation (Scoped Authorization) ──
export {
  createDelegation,
  listDelegations,
  checkAuthorization,
  recordDelegatedSpend,
  revokeDelegation,
  queryDelegationAudit,
  delegationCreateSchema,
  delegationListSchema,
  delegationCheckSchema,
} from './delegation';
export type {
  AuthorizationResult,
  DelegationStatus,
  DelegatableAction,
  AgentDelegation,
  DelegationAuditEntry,
  DelegationCreateRequest,
  DelegationCreateResponse,
  DelegationListResponse,
  DelegationRevokeResponse,
  DelegationCheckRequest,
  DelegationCheckResponse,
  DelegationCreateInput,
  DelegationListInput,
  DelegationCheckInput,
} from './delegation';

// ── Observability (Distributed Tracing & Metrics) ──
export {
  generateTraceId,
  generateSpanId,
  encodeTraceparent,
  decodeTraceparent,
  startTrace,
  createSpan,
  endSpan,
  annotateSpan,
  getTrace,
  listTraces,
  recordMetric,
  queryMetrics,
  aggregateIntoBuckets,
  percentile,
  detectAnomalies,
  listAnomalies,
  standardDeviation,
  getAgentPerformance,
  getSystemHealth,
  traceContextSchema,
  traceStartSchema,
  spanCreateSchema,
  spanUpdateSchema,
  traceListSchema,
  metricsQuerySchema,
  metricRecordSchema,
  anomalyListSchema,
  agentPerformanceSchema,
  A2A_METRICS,
} from './observability';
export type {
  TraceId,
  SpanId,
  SpanStatus,
  SpanKind,
  TraceSpan,
  SpanEvent,
  SpanLink,
  TraceContext,
  Trace,
  MetricGranularity,
  MetricDataPoint,
  MetricAggregate,
  AnomalySeverity,
  AnomalyType,
  Anomaly,
  TraceStartRequest,
  TraceStartResponse,
  SpanCreateRequest,
  SpanCreateResponse,
  SpanUpdateRequest,
  SpanUpdateResponse,
  TraceDetailResponse,
  TraceListResponse,
  MetricsResponse,
  AnomalyListResponse,
  AgentPerformanceSummary,
  SystemHealthResponse,
  TraceContextInput,
  TraceStartInput,
  SpanCreateInput,
  SpanUpdateInput,
  TraceListInput,
  MetricsQueryInput,
  MetricRecordInput,
  AnomalyListInput,
  AgentPerformanceInput,
} from './observability';

// ── Knowledge Graph (Agent Collective Memory) ──
export {
  createNode,
  updateNode,
  deleteNode,
  getNode,
  searchNodes,
  createEdge,
  deleteEdge,
  listEdges,
  traverseGraph,
  findPath,
  findContradictions,
  mergeNodes,
  applyDecay,
  reinforceNode,
  nodeCreateSchema,
  nodeUpdateSchema,
  nodeSearchSchema,
  edgeCreateSchema,
  edgeListSchema,
  traverseSchema,
  pathSchema,
  mergeSchema,
  reinforceSchema,
} from './knowledge';
export type {
  KnowledgeNodeType,
  KnowledgeNode,
  KnowledgeEdgeType,
  KnowledgeEdge,
  TraversalStrategy,
  TraversalDirection,
  PathStep,
  TraversalResult,
  PathResult,
  Contradiction,
  NodeCreateRequest,
  NodeCreateResponse,
  NodeUpdateRequest,
  NodeUpdateResponse,
  NodeSearchResponse,
  EdgeCreateRequest,
  EdgeCreateResponse,
  EdgeListResponse,
  TraverseRequest,
  TraverseResponse,
  PathRequest,
  PathResponse,
  ContradictionsResponse,
  MergeRequest,
  MergeResponse,
  DecayResponse,
  NodeCreateInput,
  NodeUpdateInput,
  NodeSearchInput,
  EdgeCreateInput,
  EdgeListInput,
  TraverseInput,
  PathInput,
  MergeInput,
  ReinforceInput,
} from './knowledge';

// ── Identity (Cryptographic Agent Trust) ──
export {
  base64urlEncode,
  base64urlDecode,
  base64urlEncodeJson,
  base64urlDecodeJson,
  generateKeyPair,
  importPublicKey,
  computeFingerprint,
  isValidPublicKey,
  signBytes,
  verifySignature,
  canonicalize,
  canonicalizeToString,
  createSignedEnvelope,
  verifyEnvelopeSignature,
  generateNonce,
  createDelegationToken,
  parseDelegationToken,
  verifyDelegationToken,
  registerPublicKey,
  listPublicKeys,
  getPrimaryKey,
  getPublicKey,
  getKeyByFingerprint,
  revokePublicKey,
  issueChallenge,
  verifyChallenge,
  verifyEnvelope,
  verifyDelegationTokenWithTrust,
  keyRegisterSchema,
  keyRevokeSchema,
  challengeRequestSchema,
  challengeVerifySchema,
  signPayloadSchema,
  verifyEnvelopeSchema,
  delegationTokenSchema,
  verifyDelegationTokenSchema,
} from './identity';
export type {
  SigningAlgorithm,
  AgentPublicKey,
  IdentityChallenge,
  ChallengeVerification,
  SignedEnvelope,
  EnvelopeSignature,
  EnvelopeVerification,
  SignedDelegationToken,
  DelegationTokenHeader,
  DelegationTokenClaims,
  IdentityProof,
  KeyRegisterRequest,
  KeyRegisterResponse,
  KeyListResponse,
  KeyRevokeRequest,
  KeyRevokeResponse,
  ChallengeRequest,
  ChallengeResponse,
  ChallengeVerifyRequest,
  ChallengeVerifyResponse,
  SignPayloadRequest,
  SignPayloadResponse,
  VerifyEnvelopeRequest,
  VerifyEnvelopeResponse,
  DelegationTokenRequest,
  DelegationTokenResponse,
  VerifyDelegationTokenRequest,
  VerifyDelegationTokenResponse,
  AgentKeysResponse,
  KeyRegisterInput,
  KeyRevokeInput,
  ChallengeRequestInput,
  ChallengeVerifyInput,
  SignPayloadInput,
  VerifyEnvelopeInput,
  DelegationTokenInput,
  VerifyDelegationTokenInput,
} from './identity';

// ── Federation (Cross-Platform Agent Collaboration) ──
export {
  registerPeer,
  acceptPeering,
  activatePeer,
  suspendPeer,
  revokePeer,
  listPeers,
  getPeerDetail,
  processCapabilitySync,
  recordSyncFailure,
  searchFederatedAgents,
  submitFederatedTask,
  handleInboundTask,
  updateFederatedTaskStatus,
  getFederatedTask,
  queryFederationAudit,
  computeEffectiveTrust,
  peerCreateSchema,
  peerListSchema,
  peerAcceptSchema,
  federatedAgentSearchSchema,
  federatedTaskSubmitSchema,
  capabilitySyncSchema,
  peerSuspendSchema,
} from './federation';
export type {
  PeerStatus,
  InboundTrustPolicy,
  FederationPeer,
  FederatedAgent,
  FederatedTask,
  FederatedTaskStatus,
  RemoteAgentManifest,
  RemoteAgentCapability,
  PeeringRequest,
  PeeringResponse,
  CapabilitySyncPayload,
  SyncResult,
  PeerCreateRequest,
  PeerCreateResponse,
  PeerListResponse,
  PeerDetailResponse,
  PeerAcceptRequest,
  PeerAcceptResponse,
  FederatedAgentSearchRequest,
  FederatedAgentSearchResponse,
  FederatedTaskSubmitRequest,
  FederatedTaskSubmitResponse,
  FederatedTaskStatusResponse,
  SyncTriggerResponse,
  PeerCreateInput,
  PeerListInput,
  PeerAcceptInput,
  FederatedAgentSearchInput,
  FederatedTaskSubmitInput,
  CapabilitySyncInput,
  PeerSuspendInput,
} from './federation';

// ── Intelligence (Adaptive Strategy Engine) ──
export {
  registerStrategy,
  getStrategy,
  listStrategies,
  retireStrategy,
  promoteStrategy,
  recordOutcome,
  getOutcomes,
  evaluatePerformance,
  recommendStrategies,
  createExperiment,
  getExperiment,
  listExperiments,
  selectStrategyForExperiment,
  evaluateExperiment,
  extractInsights,
  getInsight,
  listInsights,
  shareInsight,
  proposeEvolution,
  acceptEvolution,
  listProposals,
  getStrategyLineage,
  RegisterStrategySchema,
  RecordOutcomeSchema,
  CreateExperimentSchema,
  ProposeEvolutionSchema,
  RecommendSchema,
  ExtractInsightsSchema,
  ShareInsightSchema,
} from './intelligence';
export type {
  Strategy,
  StrategyId,
  StrategyOutcome,
  StrategyPerformance,
  Experiment,
  ExperimentId,
  Insight,
  InsightId,
  StrategyRecommendation,
  EvolutionProposal,
} from './intelligence';

// ── Ensemble (Dynamic Agent Team Composition) ──
export {
  createEnsemble,
  inviteMember,
  acceptInvite,
  removeMember,
  proposeOutput,
  voteOnRound,
  getEnsemble,
  listEnsembles as listEnsemblesQuery,
  dissolveEnsemble,
  computeRequiredVotes,
} from './ensemble/engine';
export type {
  AgentEnsemble,
  EnsembleMember,
  EnsembleInternalTask,
  ConsensusRound,
  ConsensusVote,
  ConsensusTally,
  EnsembleDissolution,
  EnsembleStatus,
  MemberRole as EnsembleMemberRole,
  MemberStatus as EnsembleMemberStatus,
  FormationStrategy,
  ConsensusPolicy,
  CreateEnsembleRequest,
  CreateEnsembleResponse,
  InviteMemberRequest,
  InviteMemberResponse,
  AcceptInviteResponse,
  ProposeOutputRequest,
  ProposeOutputResponse,
  VoteRequest as EnsembleVoteRequest,
  VoteResponse as EnsembleVoteResponse,
  DissolveRequest,
  DissolveResponse,
  ListEnsemblesResponse,
  GetEnsembleResponse,
} from './ensemble/types';
export {
  createEnsembleSchema,
  inviteMemberSchema,
  proposeOutputSchema,
  voteSchema as ensembleVoteSchema,
  dissolveSchema,
  listEnsemblesSchema,
} from './ensemble/validation';
export type {
  CreateEnsembleInput,
  InviteMemberInput,
  ProposeOutputInput,
  VoteInput as EnsembleVoteInput,
  DissolveInput,
  ListEnsemblesInput,
} from './ensemble/validation';

// ── Swarm Intelligence (Decentralized Emergent Coordination) ──
export {
  createSwarm,
  joinSwarm,
  depositPheromone,
  sensePheromones,
  reportSolution,
  evaporate,
  getSwarmStatus,
  listSwarms,
  dissolveSwarm,
  leaveSwarm,
  euclideanDistance,
  computeStrongestDirection,
  applyEvaporation,
  computeConcentrationIndex,
  adaptParameters,
  DEFAULT_SWARM_CONFIG,
} from './swarm/engine';
export type {
  Swarm,
  SwarmStatus,
  SwarmConfig,
  SwarmObjective,
  SwarmSolution,
  SwarmAgent,
  SwarmAgentStatus,
  Pheromone,
  PheromoneType,
  BehaviorRule,
  BehaviorType,
  EvaporationStrategy,
  ConvergenceCriteria,
  SwarmMetrics,
  CreateSwarmRequest,
  CreateSwarmResponse,
  JoinSwarmRequest,
  JoinSwarmResponse,
  DepositPheromoneRequest,
  DepositPheromoneResponse,
  SensePheromoneRequest,
  SensePheromoneResponse,
  ReportSolutionRequest,
  ReportSolutionResponse,
  EvaporateResponse,
  SwarmStatusResponse,
  ListSwarmsResponse,
  DissolveSwarmResponse,
} from './swarm/types';
export {
  createSwarmSchema,
  joinSwarmSchema,
  depositPheromoneSchema,
  sensePheromoneSchema,
  reportSolutionSchema,
  listSwarmsSchema,
} from './swarm/validation';
export type {
  CreateSwarmInput,
  JoinSwarmInput,
  DepositPheromoneInput,
  SensePheromoneInput,
  ReportSolutionInput,
  ListSwarmsInput,
} from './swarm/validation';

// ── Cache (Task Result Deduplication) ──
export {
  computeCacheKey,
  resolveCachePolicy,
  getEffectiveCacheParams,
  lookupCache,
  storeInCache,
  checkInFlight,
  invalidateCache,
  upsertCachePolicy,
  deleteCachePolicy,
  listCachePolicies,
  getCacheStats,
  getIntentCacheStats,
  cleanupExpiredEntries,
  cacheLookupSchema,
  cacheInvalidateSchema,
  cachePolicySchema,
  cachePolicyDeleteSchema,
  cacheStatsSchema,
  cacheWarmSchema,
} from './cache';
export type {
  CacheKey,
  CacheEntry,
  CacheEntryStatus,
  CachePolicy,
  CacheStats,
  IntentCacheStats,
  CoalescedRequest,
  CoalescedRequestStatus,
  CacheLookupRequest,
  CacheLookupResponse,
  CacheInvalidateRequest,
  CacheInvalidateResponse,
  CachePolicyRequest,
  CachePolicyResponse,
  CachePolicyDeleteResponse,
  CacheStatsResponse,
  CacheWarmRequest,
  CacheWarmResponse,
  CacheLookupResult,
  CacheStoreParams,
  InvalidationResult,
  CacheLookupInput,
  CacheInvalidateInput,
  CachePolicyInput,
  CachePolicyDeleteInput,
  CacheStatsInput,
  CacheWarmInput,
} from './cache';

// ── Pipelines (Type-Safe Multi-Agent Data-Flow Composition) ──
export {
  checkSchemaCompatibility,
  extractSchemaFields,
  extractRequiredFields,
  resolvePath,
  applyFieldMap,
  createPipeline,
  getPipeline,
  listPipelines,
  updatePipeline,
  createExecution,
  getExecution,
  updateExecution,
  executePipeline,
  cancelExecution,
  analyzeCompatibility,
  planPipeline,
  listExecutions,
  pipelineCreateSchema,
  pipelineUpdateSchema,
  pipelineListSchema,
  pipelineExecuteSchema,
  executionListSchema,
  pipelinePlanSchema,
  schemaCheckSchema,
} from './pipelines';
export type {
  SchemaCompatibility,
  CompatibilityCheck,
  FieldTypeMismatch,
  PipelineStatus,
  PipelineStage,
  StageRetryPolicy,
  Pipeline,
  ExecutionStatus,
  StageExecutionStatus,
  StageExecution,
  PipelineExecution,
  PipelinePlan,
  PlannedStage,
  PlannedAgent,
  StageCompatibilityReport,
  PipelineCreateRequest,
  PipelineCreateResponse,
  PipelineExecuteRequest,
  PipelineExecuteResponse,
  PipelineExecutionResponse,
  PipelinePlanRequest,
  PipelinePlanResponse,
  SchemaCheckRequest,
  SchemaCheckResponse,
  PipelineListResponse,
  PipelineUpdateRequest,
  PipelineUpdateResponse,
  PipelineCancelResponse,
  PipelineCreateInput,
  PipelineUpdateInput,
  PipelineListInput,
  PipelineExecuteInput,
  ExecutionListInput,
  PipelinePlanInput,
  SchemaCheckInput,
} from './pipelines';

// ── Arbitration (Dispute Resolution & Precedent System) ──
export {
  fileDispute,
  submitEvidence,
  sendDisputeMessage,
  escalateDispute,
  issueRuling,
  enforceRuling,
  fileAppeal,
  withdrawDispute,
  searchPrecedents,
  citePrecedent,
  listDisputes,
  getDisputeDetail,
  processExpiredPhases,
  calculateFilingBond,
  assessSeverity,
  FileDisputeSchema,
  SubmitEvidenceSchema,
  NegotiateSchema,
  EscalateSchema,
  IssueRulingSchema,
  AppealSchema,
  WithdrawSchema,
  PrecedentSearchSchema,
  DISPUTE_CONFIG,
} from './arbitration';
export type {
  Dispute,
  DisputePhase,
  DisputeCategory,
  DisputeSeverity,
  DisputeEvidence,
  DisputeMessage,
  DisputeRuling,
  DisputePrecedent,
  RulingOutcome,
  EnforcementAction,
  EnforcementDirective,
  ArbitratorQualification,
  SettlementOffer,
  NegotiationMessageType as DisputeNegotiationMessageType,
  EvidenceType,
  DisputeFileRequest,
  DisputeFileResponse,
  EvidenceSubmitRequest,
  EvidenceSubmitResponse,
  NegotiateRequest as DisputeNegotiateRequest,
  NegotiateResponse as DisputeNegotiateResponse,
  EscalateRequest as DisputeEscalateRequest,
  EscalateResponse as DisputeEscalateResponse,
  RuleRequest,
  RuleResponse,
  AppealRequest,
  AppealResponse,
  WithdrawRequest as DisputeWithdrawRequest,
  WithdrawResponse as DisputeWithdrawResponse,
  DisputeListResponse,
  DisputeDetailResponse,
  PrecedentSearchRequest,
  PrecedentSearchResponse,
} from './arbitration';

// ── Organizations (Agent Fleets & Hierarchical RBAC) ──
export {
  createOrg,
  getOrgDetail,
  listOrgs,
  updateOrg,
  dissolveOrg,
  inviteMember as inviteOrgMember,
  acceptInvite as acceptOrgInvite,
  updateMember as updateOrgMember,
  removeMember as removeOrgMember,
  listMembers as listOrgMembers,
  proposeCollaboration,
  acceptCollaboration,
  terminateCollaboration,
  listCollaborations,
  queryOrgAudit,
  hasPermission as hasOrgPermission,
  getEffectivePermissions as getOrgEffectivePermissions,
  getEffectiveTrustLevel,
} from './organizations/engine';
export {
  createOrgSchema,
  updateOrgSchema,
  listOrgsSchema,
  inviteMemberSchema as orgInviteMemberSchema,
  updateMemberSchema as orgUpdateMemberSchema,
  listMembersSchema as orgListMembersSchema,
  proposeCollaborationSchema,
  acceptCollaborationSchema,
  listCollaborationsSchema,
  orgAuditSchema,
} from './organizations/validation';
export type {
  CreateOrgInput,
  UpdateOrgInput,
  ListOrgsInput,
  InviteMemberInput as OrgInviteMemberInput,
  UpdateMemberInput as OrgUpdateMemberInput,
  ListMembersInput as OrgListMembersInput,
  ProposeCollaborationInput,
  AcceptCollaborationInput,
  ListCollaborationsInput,
  OrgAuditInput,
} from './organizations/validation';
export type {
  Organization,
  OrgStatus,
  OrgRole,
  OrgPermission,
  OrgSettings,
  OrgMember,
  MembershipStatus,
  OrgCollaboration,
  CollaborationStatus,
  CollaborationBillingMode,
  OrgAuditEntry,
  OrgAuditAction,
  CreateOrgRequest,
  CreateOrgResponse,
  UpdateOrgRequest,
  UpdateOrgResponse,
  ListOrgsResponse,
  OrgDetailResponse,
  InviteMemberRequest as OrgInviteMemberRequest,
  InviteMemberResponse as OrgInviteMemberResponse,
  AcceptInviteResponse as OrgAcceptInviteResponse,
  UpdateMemberRequest as OrgUpdateMemberRequest,
  UpdateMemberResponse as OrgUpdateMemberResponse,
  RemoveMemberResponse as OrgRemoveMemberResponse,
  ListMembersResponse as OrgListMembersResponse,
  ProposeCollaborationRequest,
  ProposeCollaborationResponse,
  AcceptCollaborationRequest,
  AcceptCollaborationResponse,
  TerminateCollaborationResponse,
  ListCollaborationsResponse,
  OrgAuditResponse,
} from './organizations/types';
export { ROLE_PERMISSIONS, ROLE_RANK, DEFAULT_ORG_SETTINGS } from './organizations/types';

// ── Agent Memory & Contextual Continuity (loop 16) ───────────────────
export type {
  MemoryBank,
  MemoryBankId,
  RetentionPolicy,
  Episode,
  EpisodeId,
  EpisodeType,
  EpisodeContext,
  Valence,
  RecallQuery,
  RecallWeights,
  RecalledEpisode,
  Consolidation,
  ConsolidationId,
  ConsolidationStrategy,
  ConsolidationStatus,
  MemoryShare,
  ShareId,
  ShareVisibility,
  ContinuitySession,
  ContinuitySessionId,
  CreateBankRequest,
  CreateBankResponse,
  ListBanksResponse,
  RecordEpisodeRequest,
  RecordEpisodeResponse,
  RecallResponse,
  ConsolidateRequest,
  ConsolidateResponse,
  ShareEpisodeRequest,
  ShareEpisodeResponse,
  CreateContinuitySessionRequest,
  CreateContinuitySessionResponse,
  UpdateContinuitySessionRequest,
  UpdateContinuitySessionResponse,
  ResumeContinuitySessionResponse,
  MemoryStats,
} from './memory';
export {
  createBank,
  getBank,
  listBanks,
  deleteBank,
  recordEpisode,
  getEpisode,
  listEpisodes,
  recall,
  consolidate,
  getConsolidation,
  listConsolidations,
  shareEpisode,
  revokeShare,
  listShares,
  getSharedEpisodes,
  createContinuitySession,
  getContinuitySession,
  listContinuitySessions,
  updateContinuitySession,
  resumeContinuitySession,
  getMemoryStats,
} from './memory';
export {
  CreateBankSchema,
  RecordEpisodeSchema,
  RecallSchema,
  ConsolidateSchema,
  ShareEpisodeSchema,
  RevokeShareSchema,
  CreateContinuitySessionSchema,
  UpdateContinuitySessionSchema,
} from './memory';

// ── Marketplace (Agent Capability Package Registry) ───────────────────
export type {
  PackageLicense,
  PackageVisibility,
  PackageStatus,
  PackageCategory,
  PackagePricing,
  MarketplacePackage,
  PackageMetrics,
  PackageVersion,
  DependencySpec,
  InstallStatus,
  PackageInstallation,
  PackageReview,
  DependencyResolution,
  ResolvedDependency,
  DependencyConflict,
  QualityBreakdown,
  PublishPackageRequest,
  PublishPackageResponse,
  SearchPackagesRequest,
  SearchPackagesResponse,
  InstallPackageRequest,
  InstallPackageResponse,
  SubmitReviewRequest,
  SubmitReviewResponse,
  PackageDetailResponse,
  PublishVersionRequest,
  PublishVersionResponse,
  ResolveDepsRequest,
  ResolveDepsResponse,
  ListInstalledResponse,
  ListReviewsResponse,
  MarketplaceStatsResponse,
} from './marketplace';
export {
  computeQualityScore,
  QUALITY_WEIGHTS,
  publishPackage,
  searchPackages,
  getPackageDetail,
  installPackage,
  uninstallPackage,
  submitReview,
  listReviews as listPackageReviews,
  resolveDependencies,
  publishVersion as publishPackageVersion,
  listInstalled,
  getMarketplaceStats,
} from './marketplace';
export type {
  PublishPackageParams,
  SearchParams as MarketplaceSearchParams,
  InstallParams as MarketplaceInstallParams,
  SubmitReviewParams,
  PublishVersionParams as MarketplacePublishVersionParams,
} from './marketplace';
export {
  publishPackageSchema,
  searchPackagesSchema,
  installPackageSchema,
  uninstallPackageSchema,
  submitReviewSchema,
  publishVersionSchema as marketplacePublishVersionSchema,
  resolveDepsSchema,
  listInstalledSchema,
  listReviewsSchema,
} from './marketplace';

// ── Gateway (Batch Operations, SSE Streaming, Protocol Introspection — loop 20) ──
export type {
  BatchMethod,
  BatchStep,
  BatchRequest,
  BatchStepResult,
  BatchStatus,
  BatchResponse,
  StreamEventType,
  StreamEvent,
  StreamSubscription,
  EndpointDescriptor,
  DomainDescriptor,
  IntrospectionResponse,
  IntrospectionQuery,
  InternalDispatcher,
  BatchStepInput,
  BatchRequestInput,
  StreamSubscriptionInput,
  IntrospectionQueryInput,
} from './gateway';
export {
  GATEWAY_VERSION,
  MAX_BATCH_STEPS,
  MAX_BATCH_TIMEOUT_MS,
  DEFAULT_STEP_TIMEOUT_MS,
  DEFAULT_BATCH_TIMEOUT_MS,
  MAX_STREAM_CONNECTIONS_PER_AGENT,
  ALL_STREAM_EVENT_TYPES,
  resolvePath as resolveGatewayTemplatePath,
  interpolateString,
  interpolateValue,
  extractTemplateDeps,
  resolveDependencies as resolveGatewayDependencies,
  executeBatch,
  formatSSE,
  createConnectedEvent,
  createPingEvent,
  buildIntrospection,
  BatchCycleError,
  batchRequestSchema,
  batchStepSchema,
  streamSubscriptionSchema,
  streamEventTypes,
  introspectionQuerySchema,
} from './gateway';

// ── Skill Transfer (Agent-to-Agent Knowledge Distillation — loop 18/40) ──
export type {
  DifficultyLevel,
  ModuleDelivery,
  CurriculumModule,
  PassCriteria,
  CurriculumStatus,
  Curriculum,
  SessionStatus as SkillSessionStatus,
  ModuleProgress,
  TeachingSession,
  Demonstration,
  AssessmentType,
  TestCase as SkillTestCase,
  TestResult as SkillTestResult,
  Assessment,
  SkillCertificate,
  SkillLineage,
  SkillTransferEdge,
  TeachingReputation,
  SessionRating,
  CreateCurriculumRequest,
  CreateCurriculumResponse,
  ListCurriculaResponse,
  RequestSessionRequest,
  RequestSessionResponse,
  AcceptSessionResponse as SkillAcceptSessionResponse,
  AdvanceModuleRequest,
  AdvanceModuleResponse,
  RecordDemoRequest,
  RecordDemoResponse,
  RunAssessmentRequest,
  RunAssessmentResponse,
  GetLineageResponse,
  GetTeachingReputationResponse,
  RateSessionRequest,
  RateSessionResponse,
  SearchCurriculaRequest,
  ListSessionsRequest as SkillListSessionsRequest,
  ListSessionsResponse as SkillListSessionsResponse,
  CertificateListResponse,
} from './skill-transfer';
export {
  createCurriculum,
  getCurriculum,
  listCurricula,
  updateCurriculumStatus,
  validatePrerequisiteChain,
  requestSession as requestSkillSession,
  acceptSession as acceptSkillSession,
  startSession as startSkillSession,
  getSession as getSkillSession,
  listSessions as listSkillSessions,
  advanceModule,
  recordDemonstration,
  getDemonstrations,
  computeDemoAccuracy,
  runAssessment,
  getAssessments,
  getCertificates,
  getLineage,
  getTeachingReputation,
  rateSession as rateSkillSession,
  resetStores as resetSkillTransferStores,
} from './skill-transfer';
export {
  createCurriculumSchema,
  searchCurriculaSchema,
  requestSessionSchema as requestSkillSessionSchema,
  listSessionsSchema as listSkillSessionsSchema,
  advanceModuleSchema,
  recordDemoSchema,
  runAssessmentSchema,
  rateSessionSchema,
} from './skill-transfer';
export type {
  CreateCurriculumInput,
  SearchCurriculaInput,
  RequestSessionInput as RequestSkillSessionInput,
  ListSessionsInput as ListSkillSessionsInput,
  AdvanceModuleInput,
  RecordDemoInput,
  RunAssessmentInput,
  RateSessionInput,
} from './skill-transfer';

// ── Evolution & Natural Selection ──
export type {
  Gene,
  GeneType,
  GeneValue,
  GeneConstraints,
  Genome,
  FitnessScore,
  FitnessDimension,
  Population,
  PopulationStatus,
  SelectionStrategy,
  CrossoverMethod,
  MutationType,
  Species,
  LineageRecord as EvolutionLineageRecord,
  MutationRecord,
  GenealogyNode,
  GenealogyTree,
  SeedGenomeInput,
  CreatePopulationRequest,
  CreatePopulationResponse,
  EvaluateFitnessRequest,
  EvaluateFitnessResponse,
  AdvanceGenerationResponse,
  CrossoverRequest,
  CrossoverResponse,
  MutateRequest,
  MutateResponse,
  PopulationListResponse,
  PopulationDetailResponse,
  LineageResponse as EvolutionLineageResponse,
  GenerationStats,
} from './evolution';
export {
  createPopulation,
  getPopulation as getEvolutionPopulation,
  listPopulations,
  evaluateFitness,
  selectParent,
  crossover,
  mutate,
  advanceGeneration,
  getLineage as getEvolutionLineage,
  getGenome,
  listGenomesForPopulation,
  resetEvolutionStores,
} from './evolution';
export type { CreatePopulationParams } from './evolution';
export {
  createPopulationSchema,
  listPopulationsSchema,
  evaluateFitnessSchema,
  crossoverSchema,
  mutateSchema,
} from './evolution';
export type {
  CreatePopulationInput,
  ListPopulationsInput,
  EvaluateFitnessInput,
  CrossoverInput,
  MutateInput,
} from './evolution';

// ── Trust: Progressive Trust & Dynamic Autonomy Protocol ──
export type {
  TrustDomain,
  DomainTrust,
  AgentTrustProfile,
  TrustEvent,
  TrustEventType,
  TrustSignal,
  TrustEvaluationResult,
  TrustScoreWeights,
  TrustThresholds,
  TrustTrigger,
} from './trust';
export {
  TRUST_DOMAINS,
  DEFAULT_THRESHOLDS as TRUST_DEFAULT_THRESHOLDS,
  HIGH_STAKES_THRESHOLDS as TRUST_HIGH_STAKES_THRESHOLDS,
  HIGH_STAKES_DOMAINS as TRUST_HIGH_STAKES_DOMAINS,
  DEFAULT_SCORE_WEIGHTS as TRUST_SCORE_WEIGHTS,
  AUTONOMY_ORDER,
  scoreToAutonomyLevel,
  compareAutonomy,
  getOrCreateProfile as getOrCreateTrustProfile,
  getProfile as getTrustProfile,
  listProfiles as listTrustProfiles,
  evaluateSignal as evaluateTrustSignal,
  evaluateBatch as evaluateTrustBatch,
  setManualOverride as setTrustOverride,
  liftManualOverride as liftTrustOverride,
  adjustThresholds as adjustTrustThresholds,
  getEventHistory as getTrustEventHistory,
  getDomainAutonomy,
  hasAutonomy,
  resolveExpiredProbations,
  registerCustomDomain as registerTrustDomain,
  listCustomDomains as listTrustDomains,
  resetTrustState,
} from './trust';
export {
  trustSignalSchema,
  manualOverrideSchema as trustOverrideSchema,
  liftOverrideSchema as trustLiftOverrideSchema,
  thresholdAdjustmentSchema as trustThresholdSchema,
  trustProfileQuerySchema,
  trustHistoryQuerySchema,
  batchTrustSignalSchema,
  customDomainSchema as trustCustomDomainSchema,
} from './trust';
export type {
  TrustSignalInput,
  ManualOverrideInput as TrustOverrideInput,
  LiftOverrideInput as TrustLiftOverrideInput,
  ThresholdAdjustmentInput as TrustThresholdInput,
  TrustProfileQuery,
  TrustHistoryQuery,
  BatchTrustSignalInput,
  CustomDomainInput as TrustCustomDomainInput,
} from './trust';

// ── Protocol Bridge (Universal Agent Interoperability — loop 23) ──
export type {
  ProtocolFamily,
  ProtocolVersion,
  WireFormat,
  ExternalAuthMethod,
  ProtocolAdapter,
  AdapterStatus,
  DetectionPattern,
  CapabilityMapping,
  PayloadTransform,
  StateMapping,
  DetectionResult,
  DetectionCandidate,
  MatchedPattern,
  ProtocolNegotiation,
  ProtocolPreference,
  AgreedProtocol,
  NegotiationStatus,
  CanonicalMessage,
  CanonicalMessageType,
  CanonicalAgent,
  TranslationMeta,
  TranslationSession,
  SessionParticipant,
  SessionStats,
  SessionStatus as BridgeSessionStatus,
  CompatibilityEntry,
  CompatibilityMatrixResponse,
  RegisterAdapterRequest,
  RegisterAdapterResponse,
  ListAdaptersResponse as BridgeListAdaptersResponse,
  GetAdapterResponse,
  DetectProtocolRequest,
  DetectProtocolResponse,
  TranslateMessageRequest,
  TranslateMessageResponse,
  StartNegotiationRequest,
  StartNegotiationResponse,
  RespondNegotiationRequest,
  RespondNegotiationResponse,
  CreateSessionRequest as BridgeCreateSessionRequest,
  CreateSessionResponse as BridgeCreateSessionResponse,
  SessionMessageRequest,
  SessionMessageResponse,
  ListSessionsResponse as BridgeListSessionsResponse,
} from './protocol-bridge';
export {
  registerAdapter,
  getAdapter as getBridgeAdapter,
  listAdapters as listBridgeAdapters,
  updateAdapterStatus,
  findAdapterForProtocol,
  detectProtocol,
  translateMessage,
  startNegotiation,
  respondToNegotiation,
  getNegotiation,
  createSession as createBridgeSession,
  getSession as getBridgeSession,
  listSessions as listBridgeSessions,
  closeSession as closeBridgeSession,
  sendSessionMessage,
  getCompatibilityMatrix,
  resetBridgeStores,
  BridgeError,
} from './protocol-bridge';
export type {
  RegisterAdapterParams,
  DetectProtocolParams,
  TranslateParams,
  TranslateResult,
  BridgeErrorCode,
} from './protocol-bridge';
export {
  registerAdapterSchema,
  listAdaptersSchema as listBridgeAdaptersSchema,
  detectProtocolSchema,
  translateMessageSchema,
  startNegotiationSchema,
  respondNegotiationSchema,
  createSessionSchema as bridgeCreateSessionSchema,
  sessionMessageSchema,
  listSessionsSchema as bridgeListSessionsSchema,
} from './protocol-bridge';
export type {
  RegisterAdapterInput,
  ListAdaptersInput as BridgeListAdaptersInput,
  DetectProtocolInput,
  TranslateMessageInput,
  StartNegotiationInput,
  RespondNegotiationInput,
  CreateSessionInput as BridgeCreateSessionInput,
  SessionMessageInput,
  ListSessionsInput as BridgeListSessionsInput,
} from './protocol-bridge';

// ── Consensus (Agent Collective Decision-Making — loop 25) ──
export { ConsensusEngine } from './consensus/engine';
export type {
  ConsensusAlgorithm,
  DecisionDomain,
  ProposalStatus,
  VoteChoice,
  CouncilRole,
  SplitBrainStrategy,
  ConsensusEventType,
  Proposal,
  Vote,
  VoteDelegation,
  ConsensusCouncil,
  CouncilMember,
  DomainConfig,
  DecisionOutcome,
  VoteTally,
  VetoInfo,
  ResolutionMethod,
  EnforcementAction as ConsensusTypesEnforcementAction,
  EnforcementActionType,
  ConvictionState,
  SplitBrainEvent,
  PartitionDecision,
  SplitBrainResolution,
  ConsensusAuditEntry,
} from './consensus/types';
export {
  DECISION_DOMAINS,
  SAFETY_CRITICAL_DOMAINS,
  TERMINAL_STATUSES as CONSENSUS_TERMINAL_STATUSES,
} from './consensus/types';
export {
  ConsensusAlgorithmSchema,
  DecisionDomainSchema,
  ProposalStatusSchema,
  VoteChoiceSchema,
  CouncilRoleSchema,
  SplitBrainStrategySchema,
  CreateCouncilSchema,
  AddCouncilMemberSchema,
  RemoveCouncilMemberSchema,
  CreateProposalSchema,
  OpenProposalSchema,
  CancelProposalSchema,
  ListProposalsSchema,
  CastVoteSchema,
  CreateDelegationSchema as CreateVoteDelegationSchema,
  RevokeDelegationSchema as RevokeVoteDelegationSchema,
  DetectSplitBrainSchema,
  ResolveSplitBrainSchema,
  AuditQuerySchema as ConsensusAuditQuerySchema,
  ResolveProposalSchema,
  ExecuteProposalSchema,
  UpdateConvictionSchema,
} from './consensus/validation';

// ── Intent Discovery (Semantic Matchmaking — loop 27) ──
export { IntentDiscoveryEngine, intentDiscoveryEngine } from './intent-discovery';
export type {
  IntentType,
  IntentStatus,
  PrivacyLevel,
  IntentCapabilities,
  IntentConstraints,
  MatchPreferences,
  AgentIntent,
  MatchStatus,
  MatchScoreBreakdown,
  SuggestedNegotiationParams,
  IntentMatch,
  SubscriptionFilter,
  IntentSubscription,
  MatchmakingSessionStatus,
  MatchmakingSession,
  IntentIndex,
  DomainExpertise,
  InteractionRecord,
  SemanticProfile,
  RankingAlgorithm,
  MatchmakingConfig,
  FederatedIntent,
  IntentEventType,
  IntentAuditEntry,
  PublishIntentRequest,
  UpdateIntentRequest,
  FindMatchesOptions,
  MatchmakingFeedback,
  SearchIntentsRequest,
  PropagateIntentRequest,
  ImportFederatedIntentRequest,
} from './intent-discovery';
export {
  INTENT_TYPES,
  INTENT_STATUSES,
  TERMINAL_INTENT_STATUSES,
  PRIVACY_LEVELS,
  MATCH_STATUSES,
  MATCHMAKING_SESSION_STATUSES,
  RANKING_ALGORITHMS,
  DEFAULT_MATCHMAKING_CONFIG,
} from './intent-discovery';
export {
  publishIntentSchema,
  updateIntentSchema,
  findMatchesSchema,
  startMatchmakingSchema,
  refineMatchmakingSchema,
  selectMatchSchema,
  subscribeSchema as intentSubscribeSchema,
  unsubscribeSchema as intentUnsubscribeSchema,
  searchIntentsSchema,
  getProfileSchema as intentGetProfileSchema,
  findSimilarAgentsSchema,
  propagateIntentSchema,
  importFederatedIntentSchema,
  getSessionSchema as intentGetSessionSchema,
  getIntentSchema,
} from './intent-discovery';
export type {
  PublishIntentInput,
  UpdateIntentInput,
  FindMatchesInput,
  StartMatchmakingInput,
  RefineMatchmakingInput,
  SelectMatchInput,
  SubscribeInput as IntentSubscribeInput,
  UnsubscribeInput as IntentUnsubscribeInput,
  SearchIntentsInput,
  GetProfileInput as IntentGetProfileInput,
  FindSimilarAgentsInput,
  PropagateIntentInput,
  ImportFederatedIntentInput,
  GetSessionInput as IntentGetSessionInput,
  GetIntentInput,
} from './intent-discovery';

// ── Workflow Orchestration ──
export type {
  StepType,
  StepStatus as WorkflowOrchestStepStatus,
  WorkflowStatus as WorkflowOrchestWorkflowStatus,
  CircuitBreakerState,
  CircuitBreakerConfig,
  CircuitBreakerStatus,
  RetryStrategy,
  RetryPolicy,
  StepCondition as WorkflowOrchestStepCondition,
  WorkflowStepDefinition as WorkflowOrchestWorkflowStepDefinition,
  RetryAttempt,
  WorkflowStepExecution,
  WorkflowDefinition as WorkflowOrchestWorkflowDefinition,
  WorkflowCheckpoint,
  DeadLetterEntry,
  WorkflowExecution as WorkflowOrchestWorkflowExecution,
  WorkflowEventType,
  WorkflowAuditEntry,
  DAGValidationResult,
  CreateWorkflowRequest as WorkflowOrchestCreateWorkflowRequest,
  ExecuteWorkflowRequest,
  ResumeWorkflowRequest,
  CompleteStepRequest,
  FailStepRequest,
} from './workflow-orchestration';
export {
  STEP_TYPES,
  STEP_STATUSES,
  TERMINAL_STEP_STATUSES,
  WORKFLOW_STATUSES,
  TERMINAL_WORKFLOW_STATUSES,
  CIRCUIT_BREAKER_STATES,
  RETRY_STRATEGIES,
} from './workflow-orchestration';
export {
  createWorkflowSchema,
  executeWorkflowSchema,
  completeStepSchema,
  failStepSchema,
  timeoutStepSchema,
  getExecutionSchema,
  getWorkflowSchema,
  pauseExecutionSchema,
  resumeExecutionSchema,
  cancelExecutionSchema,
  createCheckpointSchema,
  restoreCheckpointSchema,
  acknowledgeDeadLetterSchema,
  getProgressSchema,
  getAuditLogSchema,
} from './workflow-orchestration';
export type {
  CreateWorkflowInput,
  ExecuteWorkflowInput,
  CompleteStepInput,
  FailStepInput,
  TimeoutStepInput,
  GetExecutionInput,
  GetWorkflowInput,
  PauseExecutionInput,
  ResumeExecutionInput,
  CancelExecutionInput,
  CreateCheckpointInput,
  RestoreCheckpointInput,
  AcknowledgeDeadLetterInput,
  GetProgressInput,
  GetAuditLogInput,
} from './workflow-orchestration';
export { WorkflowOrchestrationEngine, workflowOrchestrationEngine } from './workflow-orchestration';

// ── Collective Cognition ──
export type {
  CognitiveMesh,
  CognitiveMeshStatus,
  MeshConfig,
  MeshStats,
  MeshCrystallization,
  Thought,
  ThoughtType,
  ThoughtRelation,
  ReasoningBranch,
  ResonanceEvent,
  DissonanceEvent,
  AttentionFocus,
  AttentionReason,
  EmergentInsight,
  SynthesisMethod,
  InsightLineage,
  MeshThinker,
  ThinkerStatus,
  CognitiveStrength,
  CreateMeshRequest,
  CreateMeshResponse,
  JoinMeshRequest,
  JoinMeshResponse,
  ContributeThoughtRequest,
  ContributeThoughtResponse,
  SynthesizeRequest,
  SynthesizeResponse,
  EndorseInsightRequest,
  EndorseInsightResponse,
  ShiftAttentionRequest,
  ShiftAttentionResponse,
  CrystallizeResponse,
  GetMeshResponse,
  ListMeshesResponse,
  GetLineageResponse as CognitionGetLineageResponse,
} from './cognition';
export {
  createMesh,
  joinMesh,
  contributeThought,
  synthesizeInsight,
  endorseInsight,
  shiftAttention,
  crystallizeMesh,
  getInsightLineage,
  getMesh,
  listMeshes,
  dissolveMesh,
} from './cognition';
export {
  createMeshSchema,
  joinMeshSchema,
  contributeThoughtSchema,
  synthesizeSchema,
  endorseInsightSchema,
  shiftAttentionSchema,
} from './cognition';
export type {
  CreateMeshInput,
  JoinMeshInput,
  ContributeThoughtInput,
  SynthesizeInput,
  EndorseInsightInput,
  ShiftAttentionInput,
} from './cognition';

// ── Temporal Intelligence & Causal Reasoning (loop 31) ──────────────────
export type {
  TemporalPrecision,
  TemporalWindow,
  TemporalCoordinate,
  CausalRelation,
  CausalNode,
  CausalEdge,
  CausalEvidence,
  CausalGraph,
  TemporalEventType,
  TemporalEvent,
  PeriodicPattern,
  Counterfactual,
  CounterfactualIntervention,
  CounterfactualOutcome,
  ProjectionMethod,
  FutureProjection,
  Prediction,
  SensitivityFactor,
  TemporalConstraintType,
  TemporalConstraint,
  TemporalPolicy,
  TemporalSchedule,
  ScheduleParticipant,
  ScheduleMilestone,
  TemporalAnomalyType,
  TemporalAnomaly,
  TemporalEngineConfig,
  VectorClock,
  CausalOrder,
} from './temporal';
export { DEFAULT_TEMPORAL_CONFIG } from './temporal';
export {
  createCausalGraph,
  addNode,
  addEdge,
  removeNode,
  removeEdge,
  topologicalSort,
  findCausalPaths,
  getCausalAncestors,
  getCausalDescendants,
  isDSeparated,
  computeCausalStrength,
  detectCausalAnomalies,
  mergeCausalGraphs,
  projectByCausalPropagation,
  projectByPatternExtrapolation,
  projectByMonteCarlo,
  projectByEnsemble,
  applyIntervention,
  computeCounterfactual,
  compareInterventions,
  findMinimalIntervention,
  attributeCausalResponsibility,
  createSchedule,
  computeCriticalPath,
  evaluateConstraint,
  evaluatePolicy,
  detectScheduleRisks,
  createVectorClock,
  tick,
  merge as mergeVectorClocks,
  compare as compareVectorClocks,
  happenedBefore,
  isConcurrent,
  createTemporalCoordinate,
  causalSort,
  detectClockSkew,
} from './temporal';

// ── Agent Morphogenesis & Dynamic Composition (loop 32) ─────────────────

export type {
  MorphOperation,
  MorphEventStatus,
  MorphParams,
  MorphEvent,
  AgentSnapshot,
  AgentCapabilitySnapshot,
  CapabilityDelta,
  SafetyCheck,
  SafetyCheckResult,
  MergedCapability,
  PartitionedCapability,
  GraftedCapability,
  EmergedCapability,
  FusionStrategy,
  FusionConfig,
  CompositeAgent,
  FissionStrategy,
  FissionConfig,
  FissionPartition,
  FissionResult,
  GraftMode,
  GraftConfig,
  ActiveGraft,
  MetamorphTrigger,
  MetamorphPhase,
  MetamorphConfig,
  MetamorphNewCapability,
  MetamorphEnhancement,
  MetamorphState,
  ReplicationVariation,
  ReplicationConfig,
  ReplicaAgent,
  MorphRegistry,
  MorphLineageNode,
  MorphLineageGraph,
  ProposeFusionRequest,
  ProposeFusionResponse,
  ConsentMorphRequest,
  ConsentMorphResponse,
  ExecuteFusionResponse,
  DefuseRequest,
  DefuseResponse,
  ProposeFissionRequest,
  ProposeFissionResponse,
  ExecuteFissionResponse,
  ReunifyRequest,
  ReunifyResponse,
  ProposeGraftRequest,
  ProposeGraftResponse,
  RevokeGraftRequest,
  RevokeGraftResponse,
  ProposeMetamorphRequest,
  ProposeMetamorphResponse,
  AdvanceMetamorphRequest,
  AdvanceMetamorphResponse,
  ProposeReplicationRequest,
  ProposeReplicationResponse,
  ExecuteReplicationResponse,
  MorphRegistryResponse,
  MorphLineageRequest,
  MorphLineageResponse,
  MorphHistoryResponse,
  RollbackMorphRequest,
  RollbackMorphResponse,
} from './morphogenesis';

export {
  proposeFusionSchema,
  defuseSchema,
  proposeFissionSchema,
  reunifySchema,
  proposeGraftSchema,
  revokeGraftSchema,
  proposeMetamorphSchema,
  advanceMetamorphSchema,
  proposeReplicationSchema,
  consentMorphSchema,
  rollbackMorphSchema,
  morphLineageSchema,
} from './morphogenesis';

export type {
  ProposeFusionInput,
  DefuseInput,
  ProposeFissionInput,
  ReunifyInput,
  ProposeGraftInput,
  RevokeGraftInput,
  ProposeMetamorphInput,
  AdvanceMetamorphInput,
  ProposeReplicationInput,
  ConsentMorphInput,
  RollbackMorphInput,
  MorphLineageInput,
} from './morphogenesis';

export {
  consentToMorph,
  proposeFusion,
  executeFusion,
  defuse,
  proposeFission,
  executeFission,
  reunify,
  proposeGraft,
  executeGraft,
  revokeGraft,
  recordGraftInvocation,
  proposeMetamorph,
  advanceMetamorph,
  proposeReplication,
  executeReplication,
  rollbackMorph,
  getMorphRegistry,
  getMorphLineage,
  getMorphHistory,
  getComposite,
  getFission,
  getActiveGraft,
  getMetamorphState,
  getAgentGrafts,
  getAgentReplicas,
} from './morphogenesis';

// ── Adversarial Resilience (Byzantine Immune System) ──
export type {
  ThreatCategory,
  ThreatSeverity,
  ThreatStatus,
  AgentThreat,
  EvidenceType as AdversarialResiEvidenceType,
  ThreatEvidence,
  DetectionMethod,
  ResponseActionType,
  ResponseStatus,
  ResponseAction,
  QuarantineLevel,
  AgentQuarantine,
  QuarantineEscalation,
  BFTPhase,
  ByzantineVoteRound,
  BFTVote,
  IntegrityProof,
  MerklePathNode,
  ProofVerification,
  ThreatSignature,
  ThreatPattern,
  BehavioralIndicator,
  NetworkHealthReport,
  AlertLevel,
  NetworkRisk,
  ReportThreatRequest,
  ReportThreatResponse,
  QuarantineAgentRequest,
  QuarantineAgentResponse,
  EscalateQuarantineRequest,
  EscalateQuarantineResponse,
  ReleaseQuarantineRequest,
  ReleaseQuarantineResponse,
  InitiateBFTRoundRequest,
  InitiateBFTRoundResponse,
  SubmitBFTVoteRequest,
  SubmitBFTVoteResponse,
  RevealBFTVoteRequest,
  RevealBFTVoteResponse,
  GenerateIntegrityProofRequest,
  GenerateIntegrityProofResponse,
  VerifyIntegrityProofRequest,
  VerifyIntegrityProofResponse,
  GetThreatIntelligenceRequest,
  GetThreatIntelligenceResponse,
  NetworkHealthResponse,
  AgentResilienceCheckRequest,
  AgentResilienceCheckResponse,
} from './adversarial-resilience';

export {
  reportThreatSchema,
  quarantineAgentSchema,
  escalateQuarantineSchema,
  releaseQuarantineSchema,
  initiateBFTRoundSchema,
  submitBFTVoteSchema,
  revealBFTVoteSchema,
  generateIntegrityProofSchema,
  verifyIntegrityProofSchema,
  getThreatIntelligenceSchema,
  agentResilienceCheckSchema,
} from './adversarial-resilience';

export type {
  ReportThreatInput,
  QuarantineAgentInput,
  EscalateQuarantineInput,
  ReleaseQuarantineInput,
  InitiateBFTRoundInput,
  SubmitBFTVoteInput,
  RevealBFTVoteInput,
  GenerateIntegrityProofInput,
  VerifyIntegrityProofInput,
  GetThreatIntelligenceInput,
  AgentResilienceCheckInput,
} from './adversarial-resilience';

export {
  reportThreat,
  updateThreatStatus,
  getActiveThreats,
  getThreat,
  quarantineAgent,
  escalateQuarantine,
  releaseQuarantine,
  getQuarantine,
  getAllQuarantines,
  isAgentAllowed,
  initiateBFTRound,
  submitBFTVoteCommitment,
  revealBFTVote,
  getBFTRound,
  getActiveBFTRounds,
  generateIntegrityProof,
  verifyIntegrityProof,
  getIntegrityProof,
  getAgentProofChain,
  getThreatIntelligence,
  getThreatSignature,
  getNetworkHealth,
  checkAgentResilience,
} from './adversarial-resilience';

// ── Metacognition (Recursive Self-Improvement) ──
export type {
  CognitiveProfile,
  DomainCompetency,
  CognitiveBias,
  BiasSeverity,
  FailurePattern,
  FailureCategory,
  IntrospectionReport,
  DecisionPoint,
  DecisionQuality,
  TaskOutcome,
  BlindSpot,
  BlindSpotType,
  BlindSpotEvidence,
  Strategy as MetacognitionStrategy,
  StrategyStatus,
  StrategyTestResult,
  ImprovementCycle,
  CyclePhase,
  CycleTrigger,
  AlignmentInvariant,
  AlignmentCheckResult,
  AlignmentViolation,
  InvariantType,
  ImprovementPropagation,
  PropagationStatus,
  ProvenanceLink,
  IntrospectRequest,
  IntrospectResponse,
  GetCognitiveProfileRequest,
  GetCognitiveProfileResponse,
  GenerateStrategiesRequest,
  GenerateStrategiesResponse,
  StartImprovementCycleRequest,
  StartImprovementCycleResponse,
  GetBlindSpotsRequest,
  GetBlindSpotsResponse,
  PropagateImprovementRequest,
  PropagateImprovementResponse,
  MetacognitionSummary,
} from './metacognition';

export {
  introspectSchema,
  generateStrategiesSchema,
  recordTestResultSchema,
  startImprovementCycleSchema,
  advanceCycleSchema,
  getCognitiveProfileSchema,
  getBlindSpotsSchema,
  adoptStrategySchema,
  propagateImprovementSchema,
  recordPropagationResponseSchema,
} from './metacognition';

export type {
  IntrospectInput,
  GenerateStrategiesInput,
  RecordTestResultInput,
  StartImprovementCycleInput,
  AdvanceCycleInput,
  GetCognitiveProfileInput,
  GetBlindSpotsInput,
  AdoptStrategyInput,
  PropagateImprovementInput,
  RecordPropagationResponseInput,
} from './metacognition';

export {
  getOrCreateProfile,
  getCognitiveProfile,
  introspect,
  getIntrospectionReport,
  getAgentReports,
  getBlindSpots,
  generateStrategies,
  getStrategy as MetacognitiongetStrategy,
  getAgentStrategies,
  recordStrategyTestResult,
  adoptStrategy,
  startImprovementCycle,
  advanceImprovementCycle,
  getImprovementCycle,
  getAgentCycles,
  checkAlignment,
  propagateImprovement,
  recordPropagationResponse,
  getPropagation,
  getAgentPropagations,
  getMetacognitionSummary,
} from './metacognition';

// ── Noosphere (Collective Intelligence & Distributed Cognition) ──
export {
  createSession as createCognitiveSession,
  joinSession as joinCognitiveSession,
  contributeThought as NoospherecontributeThought,
  endorseThought,
  createArtifact as createCognitiveArtifact,
  updateArtifact as updateCognitiveArtifact,
  signalAttention,
  fuseInsights,
  getSessionState as getCognitiveSessionState,
  concludeSession as concludeCognitiveSession,
  dissolveSession as dissolveCognitiveSession,
  detectStagnation,
} from './noosphere';

export type {
  CognitiveSession,
  SessionGoalType,
  SessionStatus,
  AttentionBudget,
  ConstitutionalConstraint,
  Thought as NoosphereThought,
  ThoughtType as NoosphereThoughtType,
  ThoughtEndorsement,
  ConstraintCheckResult,
  WorkingMemoryArtifact,
  ArtifactType,
  ArtifactRevision,
  ArtifactLock,
  AttentionSignal,
  AttentionSignalType,
  AttentionState,
  AttentionFocus as NoosphereAttentionFocus,
  FusionStrategy as NoosphereFusionStrategy,
  EmergentConclusion,
  DissentRecord,
  InsightProvenance,
  ProvenanceStep,
  ProvenanceEdge,
  SessionStats as NoosphereSessionStats,
  CreateSessionRequest,
  CreateSessionResponse,
  JoinSessionRequest,
  JoinSessionResponse,
  ContributeThoughtRequest as NoosphereContributeThoughtRequest,
  ContributeThoughtResponse as NoosphereContributeThoughtResponse,
  EndorseThoughtRequest,
  EndorseThoughtResponse,
  CreateArtifactRequest as CreateCognitiveArtifactRequest,
  CreateArtifactResponse as CreateCognitiveArtifactResponse,
  UpdateArtifactRequest as UpdateCognitiveArtifactRequest,
  UpdateArtifactResponse as UpdateCognitiveArtifactResponse,
  SignalAttentionRequest,
  SignalAttentionResponse,
  FuseInsightsRequest,
  FuseInsightsResponse,
  GetSessionStateRequest,
  GetSessionStateResponse,
  ConcludeSessionRequest,
  ConcludeSessionResponse,
} from './noosphere';

// ── Runtime Kernel (Agent Operating System) ──
export {
  spawnProcess,
  killProcess,
  suspendProcess,
  resumeProcess,
  getProcess,
  listProcesses as listKernelProcesses,
  checkCapability,
  requestCapability,
  revokeCapability,
  createIpcChannel,
  sendIpcMessage,
  receiveIpcMessages,
  closeIpcChannel,
  scheduleNext,
  getSchedulerState,
  configureScheduler,
  getResourcePressure,
  registerSubsystem,
  listSubsystems,
  updateSubsystemHealth,
  subsystemCall,
  onKernelEvent,
  bootKernel,
  shutdownKernel,
  getKernelStatus,
  getKernelMetrics,
  KernelError,
} from './runtime-kernel';
export type {
  ProcessId,
  ProcessState,
  ProcessPriority,
  ProcessDescriptor,
  CapabilityToken,
  CapabilityScope,
  CapabilityPermission,
  CapabilityCheckResult,
  CapabilityCondition,
  ResourceQuota,
  ResourceUsage,
  ResourcePressure,
  SchedulerPolicy,
  SchedulerConfig,
  SchedulerState,
  SchedulingDecision,
  IpcChannel,
  IpcChannelType,
  IpcMessage,
  IpcDeliveryResult,
  SyscallType,
  Syscall,
  SyscallResult,
  SyscallErrorCode,
  KernelEvent,
  KernelEventType,
  KernelEventHandler,
  SubsystemDescriptor,
  SubsystemHealth,
  KernelState,
  KernelStatus,
  KernelMetrics,
  SpawnProcessRequest,
  SpawnProcessResponse,
  KillProcessRequest,
  KillProcessResponse,
  SuspendProcessRequest,
  ResumeProcessRequest,
  ProcessStateChangeResponse,
  ListProcessesRequest,
  ListProcessesResponse,
  CreateIpcChannelRequest,
  CreateIpcChannelResponse,
  SendIpcMessageRequest,
  SendIpcMessageResponse,
  ReceiveIpcMessageRequest,
  ReceiveIpcMessageResponse,
  SubsystemCallRequest,
  SubsystemCallResponse,
  RequestCapabilityRequest,
  RequestCapabilityResponse,
  RegisterSubsystemRequest,
  RegisterSubsystemResponse,
  GetKernelStatusResponse,
  GetKernelMetricsResponse,
} from './runtime-kernel';

// ─── Agent Genome (Loop 38) ────────────────────────────────────────────────

export {
  createGenome,
  forkGenome,
  computeGenomeHash,
  verifyGenomeIntegrity,
  registerGenome as registerGenomeSpec,
  getGenome as getGenomeSpec,
  getLatestGenome,
  getGenomeByVersion,
  searchGenomes,
  validateGenome as validateGenomeSpec,
  diffGenomes,
  preFlightVerify,
  instantiateGenome,
  deprecateGenome,
  getLineage as getAgentGenomeLineage,
  getRegistryStats as getGenomeRegistryStats,
  GenomeError,
} from './agent-genome';

export type {
  GenomeRegistryStats,
} from './agent-genome';

export type {
  AgentGenome,
  GenomeHash,
  GenomeSpecVersion,
  GenomeLineageId,
  GenerationNumber,
  GenomeIdentity,
  CognitiveArchitecture,
  ReasoningStrategy,
  LearningMode,
  CapabilityGene,
  CapabilityMaturity,
  CapabilityProvenance,
  CapabilityProvenanceType,
  ValidationEvidence,
  ConstitutionalDna,
  ConstitutionalPrinciple,
  ConstitutionalConstraint as AgentGenomeConstitutionalConstraint,
  ConstitutionalException,
  ConstraintEnforcement,
  ResourceRequirements,
  ResourceProfile,
  ScalingPolicy,
  CommunicationProtocol,
  MessageEncoding,
  MessageTypeDescriptor,
  GenomeLineage,
  DerivationType,
  GenomeMutation,
  FitnessMetrics,
  CompositionRules,
  CompositionRole,
  GenomeCompatibility,
  GenomeIncompatibility,
  GenomeSignature,
  SignatureAlgorithm,
  GenomeRegistryEntry,
  GenomeDiff,
  GenomeDiffSummary,
  InstantiationRequest,
  InstantiationResult,
  PreFlightVerification,
  PreFlightCheck,
  RegisterGenomeRequest,
  RegisterGenomeResponse,
  GetGenomeRequest,
  GetGenomeResponse,
  SearchGenomesRequest,
  SearchGenomesResponse,
  DiffGenomesRequest,
  DiffGenomesResponse,
  ValidateGenomeRequest,
  ValidateGenomeResponse,
  GenomeValidationError,
  GenomeValidationWarning,
  VerifySignatureRequest,
  VerifySignatureResponse,
  GetLineageRequest,
  GetLineageResponse as AgentGenomeGetLineageResponse,
} from './agent-genome/types';

// ── Formal Verification (Pre-Deployment Safety Proofs) ──
export {
  verifyModel,
  composeAndVerify,
  analyzeDeadlocks,
  discoverInvariants,
  checkInvariant,
  checkLiveness,
  composeModels,
  generateCertificate,
  getCertificatesForGenome,
  verifyCertificateIntegrity,
  validateModel,
  evaluatePredicate,
  evaluateAtomicFormula,
  templateToProperty,
  VerificationError,
  _resetVerificationState,
} from './formal-verification/engine';
export type { VerificationErrorCode } from './formal-verification/engine';
export type {
  LTLOperator,
  CTLQuantifier,
  TemporalFormula,
  StatePredicate,
  AgentState,
  StateTransition,
  AgentBehaviorModel,
  StateVariable,
  FairnessConstraint,
  VerificationProperty,
  PropertyCategory,
  VerificationSpec,
  VerificationBounds,
  CompositionContext,
  CompositionOperator,
  ChannelSpec,
  PropertyVerificationResult,
  VerificationVerdict,
  CounterexampleTrace,
  CounterexampleState,
  ProofWitness,
  ProofTechnique,
  ProofCertificate,
  CertificateVerdict,
  VerificationSummary,
  CertificateSignature,
  ValidityCondition,
  StandardPropertyTemplate,
  VerifyModelRequest,
  VerifyCompositionRequest,
  VerificationResponse,
  DeadlockAnalysis,
  InvariantDiscoveryRequest,
  DiscoveredInvariant,
} from './formal-verification/types';
