export type {
  RegisteredAgent,
  AgentCapability,
  AgentTrustLevel,
  A2ATask,
  TaskIntent,
  TaskStatus,
  TaskPriority,
  TaskError,
  AgentRegisterRequest,
  AgentRegisterResponse,
  TaskSubmitRequest,
  TaskSubmitResponse,
  TaskUpdateRequest,
  TaskUpdateResponse,
  TaskStatusResponse,
  CapabilitiesResponse,
  PlatformIntent,
  AgentContext,
  ContextStoreRequest,
  ContextStoreResponse,
  ContextQueryResponse,
  RoutingPolicy,
  AgentScore,
  RoutingCandidate,
  RoutingResult,
  TaskRouteRequest,
  TaskRouteResponse,
} from './types';

export { authenticateAgent, generateAgentApiKey, getServiceDb } from './auth';
export {
  agentRegisterSchema,
  taskSubmitSchema,
  taskUpdateSchema,
  taskRouteSchema,
  taskFeedbackSchema,
  VALID_STATUS_TRANSITIONS,
  contextStoreSchema,
  contextQuerySchema,
} from './validation';
export type { ContextStoreInput, ContextQueryInput, TaskRouteInput, TaskFeedbackInput } from './validation';
export { executeIntent, isIntentSupported, listPlatformIntents, IntentNotFoundError } from './executor';
export {
  scoreCapabilityMatch,
  scoreRecency,
  scoreAgent,
  routeTask,
  fetchRoutingCandidates,
  fetchRoutingCandidatesWithReputation,
} from './router';
export type { TrustBlender, VersionContext } from './router';
export {
  submitTaskFeedback,
  getAgentReputation,
  getReputationScores,
  getReputationLeaderboard,
  blendTrustAndReputation,
  createReputationBlender,
} from './reputation';
export type { TaskFeedback, AgentReputation, SubmitFeedbackParams } from './reputation';
export {
  checkRateLimit,
  getAgentUsage,
  rateLimitHeaders,
  rateLimitBody,
  QUOTA_TIERS,
} from './rate-limiter';
export type {
  RateLimitAction,
  QuotaTier,
  RateLimitResult,
  AgentUsageSummary,
} from './rate-limiter';
export {
  createWorkflowDefinition,
  triggerWorkflow,
  advanceWorkflow,
  getWorkflowExecution,
  handleStepTaskCompletion,
  validateDAG,
  evaluateCondition,
  interpolateTemplate,
  computeProgress,
  getStepCategories,
  getWorkflowDefinition,
} from './workflow-engine';
export type {
  WorkflowDefinition,
  WorkflowExecution,
  WorkflowStatus,
  StepExecution,
  StepStatus,
  WorkflowStepDefinition,
  StepCondition,
  StepRetryPolicy,
  StepAgentTarget,
  CreateWorkflowRequest,
  TriggerWorkflowRequest,
  TriggerWorkflowResponse,
  WorkflowExecutionResponse,
} from './workflow-types';

// ── Channels (Agent-to-Agent Messaging) ──
export {
  channelCreateSchema,
  channelListSchema,
  channelAddMemberSchema,
  messageSendSchema,
  messageListSchema,
} from './channels';
export type {
  ChannelType,
  A2AChannel,
  MemberRole,
  ChannelMember,
  MessageType,
  VoteValue,
  ChannelMessage,
  ProposalTally,
  ChannelCreateRequest,
  ChannelCreateResponse,
  ChannelListResponse,
  ChannelAddMemberRequest,
  ChannelAddMemberResponse,
  MessageSendRequest,
  MessageSendResponse,
  MessageListResponse,
  ChannelCreateInput,
  ChannelListInput,
  ChannelAddMemberInput,
  MessageSendInput,
  MessageListInput,
} from './channels';

// ── Contracts (Agent Service Agreements) ──
export {
  proposeContract,
  negotiateContract,
  checkCompliance,
  listContracts,
  getContractDetail,
  terminateContract,
  findActiveContract,
  contractProposeSchema,
  contractNegotiateSchema,
  contractListSchema,
  contractTerminateSchema,
  DEFAULT_SLA,
} from './contracts';
// ── Discovery (Agent Search & Health) ──
export {
  searchAgents,
  getAgentProfile,
  recordHeartbeat,
  updateAgentProfile,
  computeAvailability,
} from './discovery';
export type {
  AgentAvailability,
  AgentHeartbeat,
  AgentHeartbeatRecord,
  AgentProfile,
  AgentSearchParams,
  AgentSearchResult,
  AgentProfileUpdate,
} from './discovery';
export {
  agentSearchSchema,
  agentHeartbeatSchema,
  agentProfileUpdateSchema,
} from './validation';
export type {
  AgentSearchInput,
  AgentHeartbeatInput,
  AgentProfileUpdateInput,
} from './validation';

export type {
  ServiceSLA,
  ServiceContract,
  ContractStatus,
  ContractPricing,
  PricingModel,
  ContractCompliance,
  SLAViolation,
  NegotiationEntry,
  NegotiationAction,
  ContractProposeRequest,
  ContractProposeResponse,
  ContractNegotiateRequest,
  ContractNegotiateResponse,
  ContractListResponse,
  ContractDetailResponse,
  ContractProposeInput,
  ContractNegotiateInput,
  ContractListInput,
  ContractTerminateInput,
} from './contracts';

// ── Governance (Agent Autonomy & Safety) ──
export {
  createPolicy,
  listPolicies,
  deactivatePolicy,
  evaluateAction,
  evaluateAgainstPolicy,
  matchesGlobList,
  matchGlob,
  isWithinTimeWindows,
  resolveEscalation,
  listEscalations,
  queryAuditLog,
  activateKillSwitch,
  liftKillSwitch,
  AUTONOMY_RANK,
  policyCreateSchema,
  policyListSchema,
  evaluateActionSchema,
  escalationResolveSchema,
  auditQuerySchema,
  killSwitchSchema,
  killSwitchLiftSchema,
} from './governance';
export type {
  AutonomyLevel,
  GovernedAction,
  TimeWindow,
  SpendLimit,
  GovernancePolicy,
  PolicyDecision,
  PolicyEvaluation,
  EvaluationRequest,
  EscalationStatus,
  EscalationRequest,
  GovernanceAuditEntry,
  SuspensionStatus,
  AgentSuspension,
  PolicyCreateRequest,
  PolicyCreateResponse,
  PolicyListResponse,
  EvaluateRequest,
  EvaluateResponse,
  EscalationResolveRequest,
  EscalationResolveResponse,
  AuditListResponse,
  KillSwitchRequest,
  KillSwitchResponse,
  KillSwitchLiftRequest,
  KillSwitchLiftResponse,
  PolicyCreateInput,
  PolicyListInput,
  EvaluateActionInput,
  EscalationResolveInput,
  AuditQueryInput,
  KillSwitchInput,
  KillSwitchLiftInput,
} from './governance';

// ── Billing (Token Economy & Ledger) ──
export {
  getOrCreateWallet,
  getWallet,
  setWalletStatus,
  deposit,
  computeCost,
  settleTask,
  listTransactions,
  getSpendSummary,
  depositSchema,
  settleTaskSchema,
  costEstimateSchema,
  transactionListSchema,
} from './billing';
export type {
  AgentWallet,
  WalletStatus,
  LedgerTransaction,
  TransactionType,
  TransactionStatus,
  SettlementResult,
  CostEstimate,
  SpendSummary,
  WalletResponse,
  DepositRequest,
  DepositResponse,
  SettleTaskRequest,
  SettleTaskResponse,
  TransactionListResponse,
  SpendSummaryResponse,
  CostEstimateRequest,
  CostEstimateResponse,
  DepositInput,
  SettleTaskInput,
  CostEstimateInput,
  TransactionListInput,
} from './billing';

// ── Auctions (Task Marketplace & Bidding) ──
export {
  createAuction,
  listAuctions,
  getAuctionDetail,
  placeBid,
  awardAuction,
  cancelAuction,
  withdrawBid,
  evaluateBids,
  computeDutchPrice,
  auctionCreateSchema,
  auctionListSchema,
  bidCreateSchema,
  auctionAwardSchema,
  DEFAULT_EVALUATION_WEIGHTS,
} from './auctions';
export type {
  AuctionType,
  AuctionStatus,
  TaskAuction,
  EvaluationWeights,
  BidStatus,
  AuctionBid,
  BidScoreBreakdown,
  AuctionCreateRequest,
  AuctionCreateResponse,
  AuctionListResponse,
  AuctionDetailResponse,
  BidCreateRequest,
  BidCreateResponse,
  AuctionAwardRequest,
  AuctionAwardResponse,
  AuctionCancelResponse,
  AuctionCreateInput,
  AuctionListInput,
  BidCreateInput,
  AuctionAwardInput,
} from './auctions';
