/**
 * A2A Emergent Protocol Synthesis — Public API
 *
 * The capstone module (Loop 40) that enables agents to autonomously synthesize,
 * verify, negotiate, and evolve new communication protocols.
 */

export type {
  ProtocolId,
  ProtocolVersion,
  SynthesisSessionId,
  ProposalId,
  ProtocolMessageType,
  ProtocolState,
  ProtocolTransition,
  StateInvariant,
  ProtocolRole,
  ProtocolStatus,
  ProtocolCategory,
  SynthesizedProtocol,
  ConstitutionalConstraint,
  ConstraintCategory,
  VerificationResult,
  VerificationStatus,
  CounterexampleTrace,
  ProtocolApproval,
  SynthesisStrategy,
  SessionStatus,
  SynthesisSession,
  ProtocolProposal,
  ProposalVote,
  SynthesisTelemetry,
  CommunicationGap,
  ProtocolEvolutionRecord,
  EvolutionDriver,
  ProtocolMutation,
  ProtocolTemplate,
  TemplateParameter,
  StartSynthesisRequest,
  StartSynthesisResponse,
  SubmitProposalRequest,
  SubmitProposalResponse,
  VoteOnProposalRequest,
  VoteOnProposalResponse,
  VerifyProtocolRequest,
  VerifyProtocolResponse,
  DetectGapsRequest,
  DetectGapsResponse,
  EvolveProtocolRequest,
  EvolveProtocolResponse,
  ListProtocolsRequest,
  ListProtocolsResponse,
  GetProtocolResponse,
  ApproveProtocolRequest,
  ApproveProtocolResponse,
  DeprecateProtocolRequest,
  DeprecateProtocolResponse,
  RevokeProtocolRequest,
  RevokeProtocolResponse,
  InstantiateTemplateRequest,
  InstantiateTemplateResponse,
  ListTemplatesResponse,
} from './types';

export { DEFAULT_CONSTITUTIONAL_CONSTRAINTS } from './types';

export {
  startSynthesis,
  submitProposal,
  voteOnProposal,
  verifyProtocol,
  approveProtocol,
  activateProtocol,
  deprecateProtocol,
  revokeProtocol,
  detectCommunicationGaps,
  evolveProtocol,
  registerTemplate,
  listTemplates,
  instantiateFromTemplate,
  getProtocol,
  listProtocols,
  getSession,
  getGaps,
  getEvolutionHistory,
  getAuditLog,
} from './engine';

export {
  startSynthesisSchema,
  submitProposalSchema,
  voteOnProposalSchema,
  verifyProtocolSchema,
  detectGapsSchema,
  evolveProtocolSchema,
  listProtocolsSchema,
  approveProtocolSchema,
  deprecateProtocolSchema,
  revokeProtocolSchema,
  instantiateTemplateSchema,
} from './validation';

export type {
  StartSynthesisInput,
  SubmitProposalInput,
  VoteOnProposalInput,
  VerifyProtocolInput,
  DetectGapsInput,
  EvolveProtocolInput,
  ListProtocolsInput,
  ApproveProtocolInput,
  DeprecateProtocolInput,
  RevokeProtocolInput,
  InstantiateTemplateInput,
} from './validation';
