/**
 * Universal Agent Protocol Bridge — Public API
 *
 * Enables cross-platform agent communication by translating between
 * protocol families (Google A2A, OpenAI Agents, LangChain, AutoGen,
 * MCP, and custom protocols) in real-time.
 */

export {
  registerAdapter,
  getAdapter,
  listAdapters,
  updateAdapterStatus,
  findAdapterForProtocol,
  detectProtocol,
  translateMessage,
  startNegotiation,
  respondToNegotiation,
  getNegotiation,
  createSession,
  getSession,
  listSessions,
  closeSession,
  sendSessionMessage,
  getCompatibilityMatrix,
  resetBridgeStores,
  BridgeError,
} from './engine';
export type {
  RegisterAdapterParams,
  DetectProtocolParams,
  TranslateParams,
  TranslateResult,
  BridgeErrorCode,
} from './engine';

export {
  registerAdapterSchema,
  listAdaptersSchema,
  detectProtocolSchema,
  translateMessageSchema,
  startNegotiationSchema,
  respondNegotiationSchema,
  createSessionSchema,
  sessionMessageSchema,
  listSessionsSchema,
} from './validation';
export type {
  RegisterAdapterInput,
  ListAdaptersInput,
  DetectProtocolInput,
  TranslateMessageInput,
  StartNegotiationInput,
  RespondNegotiationInput,
  CreateSessionInput,
  SessionMessageInput,
  ListSessionsInput,
} from './validation';

export type {
  ProtocolFamily,
  ProtocolVersion,
  WireFormat,
  ExternalAuthMethod,
  ProtocolAdapter,
  AdapterStatus,
  DetectionPattern,
  CapabilityMapping,
  PayloadTransform,
  StateMapping,
  DetectionResult,
  DetectionCandidate,
  MatchedPattern,
  ProtocolNegotiation,
  ProtocolPreference,
  AgreedProtocol,
  NegotiationStatus,
  CanonicalMessage,
  CanonicalMessageType,
  CanonicalAgent,
  TranslationMeta,
  TranslationSession,
  SessionParticipant,
  SessionStats,
  SessionStatus,
  CompatibilityEntry,
  CompatibilityMatrixResponse,
  RegisterAdapterRequest,
  RegisterAdapterResponse,
  ListAdaptersResponse,
  GetAdapterResponse,
  DetectProtocolRequest,
  DetectProtocolResponse,
  TranslateMessageRequest,
  TranslateMessageResponse,
  StartNegotiationRequest,
  StartNegotiationResponse,
  RespondNegotiationRequest,
  RespondNegotiationResponse,
  CreateSessionRequest,
  CreateSessionResponse,
  SessionMessageRequest,
  SessionMessageResponse,
  ListSessionsResponse,
} from './types';
