import type { Metadata } from 'next';
import Link from 'next/link';
import { BreadcrumbJsonLd } from '@/components/JsonLd';
import SiteNav from '@/components/SiteNav';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description:
    'Terms of Service for Rare Agent Work. Covers account usage, purchases, subscriptions, consulting engagements, API access, intellectual property, and liability.',
  alternates: {
    canonical: 'https://rareagent.work/terms',
  },
  openGraph: {
    title: 'Terms of Service | Rare Agent Work',
    description:
      'Terms of Service governing use of Rare Agent Work reports, subscriptions, consulting, and API access.',
    url: 'https://rareagent.work/terms',
    siteName: 'Rare Agent Work',
    type: 'website',
    images: [{ url: '/og-image.png', width: 1200, height: 630, alt: 'Rare Agent Work Terms of Service' }],
  },
};

const EFFECTIVE_DATE = 'March 14, 2026';

const sections = [
  {
    title: '1. Acceptance of terms',
    content: [
      'By accessing or using Rare Agent Work ("the Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree, do not use the Service.',
      'We may update these Terms from time to time. Continued use after changes constitutes acceptance. Material changes will be communicated via email or site notice at least 14 days before taking effect.',
      '"You" refers to any individual or entity accessing the Service. "We," "us," and "our" refer to Rare Agent Work, operated by Michael Fethe.',
    ],
  },
  {
    title: '2. Accounts',
    content: [
      'You may browse public content without an account. An account is required for purchases, subscriptions, AI chat, API keys, and form submissions.',
      'You are responsible for maintaining the security of your account credentials. Notify us immediately at <a href="mailto:hello@rareagent.work" class="text-cyan-300 hover:text-cyan-200 underline">hello@rareagent.work</a> if you suspect unauthorized access.',
      'We reserve the right to suspend or terminate accounts that violate these Terms, engage in abusive behavior, or attempt to circumvent rate limits or access controls.',
      'You must be at least 16 years old to create an account.',
    ],
  },
  {
    title: '3. Purchases and subscriptions',
    content: [
      '<strong>One-time purchases.</strong> Individual reports are sold as one-time purchases with lifetime access. Once purchased, you retain access to the report version available at the time of purchase.',
      '<strong>Subscriptions.</strong> Newsletter, Starter, and Operator Access subscriptions are billed monthly via Stripe. You may cancel at any time; access continues through the end of the current billing period.',
      '<strong>Refunds.</strong> We offer a 14-day refund policy for report purchases and subscriptions. If you are unsatisfied, email <a href="mailto:hello@rareagent.work" class="text-cyan-300 hover:text-cyan-200 underline">hello@rareagent.work</a> within 14 days of purchase for a full refund. Refunds for subscriptions apply to the most recent billing cycle only.',
      '<strong>Pricing changes.</strong> We may adjust pricing for future purchases and subscription renewals. Existing subscriptions will receive 30 days notice before any price increase takes effect.',
      'All prices are in USD. You are responsible for any applicable taxes in your jurisdiction.',
    ],
  },
  {
    title: '4. Content and intellectual property',
    content: [
      'All reports, articles, news commentary, research, and site content are the intellectual property of Rare Agent Work unless otherwise noted.',
      '<strong>Personal use.</strong> Purchased reports and subscription content are licensed for your personal or internal team use. You may share insights and quote reasonable excerpts with attribution.',
      '<strong>Restrictions.</strong> You may not redistribute, resell, or publicly republish full reports or substantial portions of paid content. You may not use automated systems to scrape or bulk-download content beyond what our public API provides.',
      '<strong>API content.</strong> Data accessed through our public API (/api/v1/*) may be used in your applications and agent systems, subject to rate limits. Attribution to Rare Agent Work is appreciated but not required for API data.',
      '<strong>Your submissions.</strong> Content you submit through forms (assessments, work submissions) remains yours. You grant us a limited license to use it for the purpose of fulfilling your request (review, consulting, specialist matching).',
    ],
  },
  {
    title: '5. AI chat and generated content',
    content: [
      'The AI chat feature provides responses generated by third-party language models (Anthropic, OpenAI, Google). These responses are informational and should not be treated as professional advice.',
      'AI-generated responses may contain errors, outdated information, or inaccuracies. You are responsible for verifying any information before acting on it.',
      'Usage is subject to per-tier token budgets and rate limits as described on our <a href="/pricing" class="text-cyan-300 hover:text-cyan-200 underline">pricing page</a>. We reserve the right to adjust limits to maintain service quality.',
      'We do not use your chat inputs to train models. Conversations may be logged for abuse prevention and are subject to our <a href="/privacy" class="text-cyan-300 hover:text-cyan-200 underline">Privacy Policy</a>.',
    ],
  },
  {
    title: '6. Consulting and professional services',
    content: [
      'Consulting services (Operator Review, Implementation Rescue, Architecture Review) are scoped engagements initiated through our intake forms and confirmed via separate written agreement.',
      'Deliverables, timelines, and fees for consulting work are agreed upon before engagement begins. These Terms govern the platform; individual consulting engagements may have additional terms.',
      'Consulting recommendations reflect our professional judgment but do not constitute guarantees of outcomes. Implementation decisions and their consequences remain your responsibility.',
      'The Network matching service provides curated introductions to specialists. We vet participants but do not guarantee the quality of work performed by third-party specialists.',
    ],
  },
  {
    title: '7. API access',
    content: [
      'API keys grant programmatic access to our public endpoints. You are responsible for keeping your API keys secure and for all activity under your keys.',
      'Rate limits are enforced per tier. Attempting to circumvent rate limits, using multiple accounts to increase limits, or engaging in abusive API usage may result in key revocation and account suspension.',
      'We may modify, deprecate, or discontinue API endpoints with reasonable notice. Breaking changes will be communicated at least 30 days in advance where feasible.',
      'The API is provided "as is." We aim for high availability but do not guarantee uptime or response-time SLAs for the public API.',
    ],
  },
  {
    title: '8. Acceptable use',
    content: [
      'You agree not to use the Service to: violate any law or regulation; infringe on intellectual property rights; transmit malware or malicious code; attempt to gain unauthorized access to our systems; harass, abuse, or harm others; or interfere with the operation of the Service.',
      'Automated access is permitted only through our documented API endpoints and within published rate limits.',
      'We reserve the right to remove content or restrict access at our discretion if we determine usage violates these Terms.',
    ],
  },
  {
    title: '9. Disclaimers',
    content: [
      'The Service is provided "as is" and "as available" without warranties of any kind, express or implied, including but not limited to merchantability, fitness for a particular purpose, or non-infringement.',
      'Research reports represent our analysis at the time of publication. The AI and agent systems landscape changes rapidly; we do not warrant that content will remain accurate indefinitely.',
      'We do not guarantee that the Service will be uninterrupted, error-free, or free of harmful components.',
    ],
  },
  {
    title: '10. Limitation of liability',
    content: [
      'To the maximum extent permitted by law, Rare Agent Work and its operator shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service.',
      'Our total liability for any claim arising from these Terms or the Service shall not exceed the amount you paid to us in the 12 months preceding the claim.',
      'These limitations apply regardless of the theory of liability (contract, tort, strict liability, or otherwise), even if we have been advised of the possibility of such damages.',
    ],
  },
  {
    title: '11. Governing law and disputes',
    content: [
      'These Terms are governed by the laws of the United States. Any disputes shall be resolved through good-faith negotiation first.',
      'If negotiation fails, disputes shall be resolved through binding arbitration under the rules of the American Arbitration Association, conducted remotely where possible.',
      'Nothing in these Terms limits your right to seek injunctive relief in a court of competent jurisdiction.',
    ],
  },
  {
    title: '12. Termination',
    content: [
      'You may close your account at any time by contacting us. Upon closure, your access to paid content and services will end at the conclusion of any active billing period.',
      'We may suspend or terminate your access for violation of these Terms, with notice where practicable.',
      'Sections that by their nature should survive termination (intellectual property, limitation of liability, governing law) will survive.',
    ],
  },
  {
    title: '13. Contact',
    content: [
      'Questions about these Terms: <a href="mailto:hello@rareagent.work" class="text-cyan-300 hover:text-cyan-200 underline">hello@rareagent.work</a>',
      'Privacy-related requests: <a href="mailto:privacy@rareagent.work" class="text-cyan-300 hover:text-cyan-200 underline">privacy@rareagent.work</a>',
      'Rare Agent Work is operated by Michael Fethe.',
    ],
  },
];

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#050816] text-slate-100">
      <SiteNav primaryCta={{ label: 'Browse Reports', href: '/reports' }} />
      <BreadcrumbJsonLd
        items={[
          { name: 'Home', url: 'https://rareagent.work' },
          { name: 'Terms of Service', url: 'https://rareagent.work/terms' },
        ]}
      />

      <main className="mx-auto max-w-4xl px-4 py-16 sm:px-6 lg:px-8">
        <section>
          <p className="text-sm font-semibold uppercase tracking-[0.24em] text-cyan-300">Legal</p>
          <h1 className="mt-3 text-4xl font-bold tracking-tight text-white sm:text-5xl">Terms of Service</h1>
          <p className="mt-4 text-sm text-slate-400">Effective date: {EFFECTIVE_DATE}</p>
          <p className="mt-5 max-w-3xl text-lg leading-8 text-slate-300">
            These terms govern your use of Rare Agent Work, including reports, subscriptions, consulting services,
            AI chat, and API access. Please read them carefully.
          </p>
        </section>

        <div className="mt-12 space-y-10">
          {sections.map((section) => (
            <section key={section.title} className="rounded-3xl border border-white/10 bg-white/[0.04] p-6">
              <h2 className="text-xl font-semibold text-white">{section.title}</h2>
              <ul className="mt-4 space-y-3 text-sm leading-7 text-slate-300">
                {section.content.map((item, i) => (
                  <li key={i} className="flex gap-3">
                    <span className="mt-0.5 shrink-0 text-cyan-300">•</span>
                    <span dangerouslySetInnerHTML={{ __html: item }} />
                  </li>
                ))}
              </ul>
            </section>
          ))}
        </div>

        <section className="mt-12 rounded-3xl border border-cyan-400/20 bg-cyan-400/10 p-6">
          <p className="text-sm font-semibold uppercase tracking-[0.24em] text-cyan-200">Related</p>
          <div className="mt-4 flex flex-wrap gap-3">
            <Link
              href="/privacy"
              className="inline-flex rounded-full bg-cyan-400 px-5 py-3 text-sm font-semibold text-slate-950 hover:bg-cyan-300"
            >
              Privacy Policy
            </Link>
            <Link
              href="/trust"
              className="inline-flex rounded-full border border-white/15 px-5 py-3 text-sm font-semibold text-white hover:bg-white/5"
            >
              Trust Controls
            </Link>
          </div>
        </section>
      </main>
    </div>
  );
}
